%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Left Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 141.91207558997834
Camera1.fy: 141.859974124345
Camera1.cx: 163.32755799726402
Camera1.cy: 92.74057160125506

# distortion parameters
Camera1.k1: -0.059763063867239015
Camera1.k2: 0.02245361844814379
Camera1.p1: -0.0015313555346179687
Camera1.p2: 0.0014249648021982895

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 141.91207558997834
Camera2.fy: 141.859974124345
Camera2.cx: 163.32755799726402
Camera2.cy: 92.74057160125506

# distortion parameters
Camera2.k1: -0.059763063867239015
Camera2.k2: 0.02245361844814379
Camera2.p1: -0.0015313555346179687
Camera2.p2: 0.0014249648021982895
    
# Transformation matrix from right camera to left camera
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [ 0.99997655, 0.00033931, 0.00683997, 0.12001843,
          -0.00036066, 0.99999507, 0.00312027,  -0.0000077,
          -0.00683888, -0.00312266, 0.99997174, -0.00332633,
          0.0,         0.0,         0.0,        1.0]

# Overlapping area between images (to be updated)
Camera1.overlappingBegin: 0
Camera1.overlappingEnd: 960

Camera2.overlappingBegin: 0
Camera2.overlappingEnd: 960

# Camera resolution
Camera.width: 336
Camera.height: 188

# Camera frames per second 
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 40.0

#--------------------------------------------------------------------------------------------
# IMU Parameters
#--------------------------------------------------------------------------------------------

# Transformation from body-frame (imu) to left camera
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [ 0.036105853, 0.004721243, 0.999336819, 0.002431559,
          -0.999330928, -0.005669635, 0.036132426, -0.020677447,
          0.005836465, -0.999972782, 0.004513377, -0.003831893,
          0.0, 0.0, 0.0, 1.0]


# IMU noise
IMU.NoiseGyro: 0.05067296223017242  # Gyroscope noise density
IMU.NoiseAcc: 0.25713221331271446   # Accelerometer noise density
IMU.GyroWalk: 0.0648427598008084    # Gyroscope random walk
IMU.AccWalk: 0.32913431324293174    # Accelerometer random walk
IMU.Frequency: 200.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0

# System.LoadAtlasFromFile: "ZED2_stereo_room_merged"
# System.SaveAtlasToFile: "ZED2_stereo_room_merged2"
