%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Left Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 501.5339583084979
Camera1.fy: 499.21534683693807
Camera1.cx: 487.882700425182 
Camera1.cy: 264.1706400682822

# distortion parameters
Camera1.k1: -0.028186241190578692 
Camera1.k2: 0.017404512191551674
Camera1.p1: -0.0015435256634181572
Camera1.p2: -0.004205123883372731

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 503.187195910098
Camera2.fy: 502.5952785049678
Camera2.cx: 488.91641037549624
Camera2.cy: 266.28724208200714

# distortion parameters
Camera2.k1: -0.04078614871347336
Camera2.k2: 0.013853547225536044
Camera2.p1: -0.0007901542717562483
Camera2.p2: -0.0032538255889693443
    
# Transformation matrix from right camera to left camera
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [ 0.99997655, 0.00033931, 0.00683997, 0.11705496,
          -0.00036066, 0.99999507, 0.00312027, 0.00019689,
          -0.00683888, -0.00312266, 0.99997174, -0.00332633,
          0.0,         0.0,         0.0,        1.0]

# Overlapping area between images (to be updated)
Camera1.overlappingBegin: 0
Camera1.overlappingEnd: 960

Camera2.overlappingBegin: 0
Camera2.overlappingEnd: 960

# Camera resolution
Camera.width: 960
Camera.height: 540

# Camera frames per second 
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 40.0

#--------------------------------------------------------------------------------------------
# IMU Parameters
#--------------------------------------------------------------------------------------------

# Transformation from body-frame (imu) to left camera
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [ 0.06159749, -0.00539653, 0.99808648, -0.00183001, 
          -0.99563516, 0.06991696, 0.06182424, 0.00526778, 
          -0.07011681, -0.99753822, -0.00106627, 0.00138844,
           0., 0., 0., 1. ]

# IMU noise
IMU.NoiseGyro: 0.13665520491400387  # 1.6968e-04 
IMU.NoiseAcc: 1.102544244729265 # 2.0000e-3
IMU.GyroWalk: 2.66e-05
IMU.AccWalk: 0.000433 # 3.0000e-3
IMU.Frequency: 200.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0

# System.LoadAtlasFromFile: "ZED2_stereo_room_merged"
# System.SaveAtlasToFile: "ZED2_stereo_room_merged2"
